name: BKNY.Life
favicon: null
layout_spectrum: 0.90532
typography_spectrum: 0.26637
title: Brooklyn & New York City Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff8ff'
    - '#000000'
    - '#fdc82e'
    - '#ee0c19'
    - '#44567c'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
